import './asset/image/food/protein_powder_whey.jpg'
import './asset/image/food/milk_skimmed_sainsbury.jpg'
import './asset/image/food/chicken_breast_raw_asda.jpg'
import './asset/image/food/lentils_red_tsr.jpg'
import './asset/image/food/pepper_red_bell.jpg'
import './asset/image/food/yogurt_fage_total_zero.jpg'
import './asset/image/food/granola_tropical.jpg'
import './asset/image/food/blueberries_asda.jpg'
import './asset/image/food/banana.jpg'
import './asset/image/food/rice_basmati_sainsbury.jpg'
import './asset/image/food/rice_white_sainsbury.jpg'
import './asset/image/food/vegetable_mixed_canned.jpg'
import './asset/image/food/ketchup.jpg'


